=== politecnicojic2022-1/HechosHistoricos/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechoHistorico)+>
<!ATTLIST HechosHistoricos version CDATA #FIXED "1.1"
                           clave NMTOKEN #REQUIRED
                           >
<!ATTLIST HechosHistoricos xml:lang (es|en) #REQUIRED>
<!ATTLIST HechoHistorico descripcion CDATA #IMPLIED
                         autor CDATA #FIXED 'oscar'>
<!ELEMENT HechoHistorico (Fecha, Epoca?, PersonajeDestacado*, FechaRelevante)?>
<!ELEMENT Epoca (EPOCA1 | EPOCA2)>
<!ELEMENT EPOCA1 (#PCDATA)>
<!ELEMENT EPOCA2 (#PCDATA)>
<!ELEMENT PersonajeDestacado ANY>
<!ATTLIST PersonajeDestacado paisOrigen (FRANCIA|ESPAÑA|ALEMANIA|JAPON|EEUU) #REQUIRED
                             cedula ID #IMPLIED
                             cedulaHermano IDREF #IMPLIED
                             cedulasPrimos IDREFS #IMPLIED>

<!ELEMENT FechaRelevante EMPTY>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT FechaNacimiento (#PCDATA)>
<!ELEMENT Fecha (#PCDATA | FormatoFecha)*>
<!ELEMENT FormatoFecha (Dia, Mes, Año)>
<!ELEMENT Dia (#PCDATA)>
<!ELEMENT Año (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>

=== politecnicojic2022-1/HechosHistoricos/HechosHistoricos.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">
<HechosHistoricos>
    <HechoHistorico descripcion="">
        <Fecha>
            <FormatoFecha>
            <Dia>01</Dia>
            <Mes>01</Mes>
            <AÃ±o>2022</AÃ±o>
            </FormatoFecha>
        </Fecha>
        <Epoca>
            <EPOCA1></EPOCA1>
        </Epoca>
        <PersonajeDestacado>
            Test persona <Nombre></Nombre> y fecha de nacimiento: <FechaNacimiento></FechaNacimiento>
        </PersonajeDestacado>
        <FechaRelevante/>
    </HechoHistorico>
    <HechoHistorico descripcion="">
        <Fecha>
            2022-10-09
        </Fecha>
        <Epoca>
            <EPOCA2></EPOCA2>
        </Epoca>
        <PersonajeDestacado></PersonajeDestacado>
        <PersonajeDestacado></PersonajeDestacado>
        <FechaRelevante/>
    </HechoHistorico>
</HechosHistoricos>
